name: Mirror to Personal Repository

on: 
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full mirror
          
      - name: Push to personal repository
        run: |
          # Configure Git identity for the push
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"


          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TK }}@github.com/ReavesX/CodingUnited.git
          
          # Ensure the remote URL is added correctly 
          git remote -v
          
          # Push everything
          git push --mirror mirror
